apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s-deployment
  labels:
    name: hello-k8s-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hello-k8s-deployment
    spec:
      containers:
      - name: hello-k8s-container
        image: gcr.io/k8s-demo-nyc/imageflipper:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      nodeSelector:
        cpu: n1-standard-1