apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-k8s-blue-green-deployment
  labels:
    name: hello-k8s-blue-green-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: hello-k8s-blue-green-deployment
    spec:
      containers:
      - name: hello-k8s-blue-green-container
        image: gcr.io/k8s-demo-nyc/imageflipper:2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080