apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-green-svc
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: hello-k8s-green-deployment
  type: LoadBalancer