apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flip-microservice-deployment
  labels:
    name: flip-microservice-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: flip-microservice-deployment
    spec:
      containers:
      - name: flip-microservice-container
        image: gcr.io/k8s-demo-nyc/imageflipper:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      nodeSelector:
        cpu: n1-standard1-2
